### ISSUE TITLE
Availability of Weights

### ISSUE THREAD

**Issue by martinezmatias** [zjulgc/llmpeft4apr#1]
Hello
Would be possible to share the weights? e.g., on zenodo for a matter of space.
Thanks
Matias

**Comment by zjulgc** [comment]
Apologies for the delay; We have been occupied with other tasks recently. We'll release the weights as soon as possible.

**Comment by zjulgc** [comment]
We have released the weights on HuggingFace, and  you can find the detail in README. So I close this issue.

**Comment by martinezmatias** [comment]
Great, thanks a lot
Best regards
Matias
